### ISSUE TITLE
Escape problem for a shell command

### ISSUE THREAD

**Issue by guorenxi** [EnlighterJS/docs#5]
The shell command:

`latestVer=$(curl -s 'http://nginx.org/en/download.html' | sed 's/\'$'\n''</g' | sed -n '/Stableversion$/,$ p' | egrep -m1 -o '/download/nginx-.+\.tar\.gz')`

was translated to:

`latestVer=$(curl -s 'http://nginx.org/en/download.html' | sed 's/<!--\'$'\n''</g' | sed -n '/-->Stableversion$/,$ p' | egrep -m1 -o '/download/nginx-.+\.tar\.gz')`

Any workaround?

Thanks.

**Comment by AndiDittrich** [comment]
don't forget to escape the html sequence `<`
