### ISSUE TITLE
How to add an external DIV class?

### ISSUE THREAD

**Issue by wanghuaimin2024** [EnlighterJS/docs#6]
Hello, I am using this plugin on Wordpress now, but the code format generated by the plugin is:
.
.
.
&#60；div class="enlighter-default ...">...&#60；/div>
&#60；pre class=''EnlighterJSRAW enlighter-origin'>...&#60；/pre>
.
.
.
, for better layout, I want to add a div outside, like this:
.
.
.
&#60；figure class="...">
&#60；div class="enlighter-default ...">...&#60；/div>
&#60；pre class=''EnlighterJSRAW enlighter-origin'>...&#60；/pre>
&#60；/figure>
.
.
.
May I ask what should be done?

您好，我现在是在Wordpress上使用该插件，但插件生成的代码格式是:
.
.
.
&#60；div class="enlighter-default ...">...&#60；/div>
&#60；pre class=''EnlighterJSRAW enlighter-origin'>...&#60；/pre>
.
.
.
，为了更好的排版，我想在外部加一个div,类似这样：
.
.
.
&#60；figure class="...">
&#60；div class="enlighter-default ...">...&#60；/div>
&#60；pre class=''EnlighterJSRAW enlighter-origin'>...&#60；/pre>
&#60；/figure>
.
.
.
可以问下应该怎么做吗?

**Comment by AndiDittrich** [comment]
Hi,

depending on your used Wordpress Editor you have the following options:

* Gutenberg: create a custom wrapper block which creates the wanted markup and place the Enlighter block within
* TinyMCE/Text: edit the html manually or create a custom shortcode
